name: output info
on: workflow_dispatch
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: github context
              run: echo "The person who triggered this pipeline is:${{ toJson(github.repository_owner)}}"