name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12

    - name: Install dependencies
      run: |
        npm i
        npm run build

    - name: Build and deploy
      uses: JamesIves/github-pages-deploy-action@v4
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        BRANCH: gh-pages
        FOLDER: build