name: Lint, Test & Build
on: [push, workflow_dispatch]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: install dependencies
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: lint
              run: npm i -g lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: install dependencies
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: test
              run: npm test
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: install dependencies
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: build
              run: npm build
